### ISSUE TITLE
Buttons work in Safari only when set to ignore mode

### ISSUE THREAD

**Issue by Nyan969** [A1rPun/vue-quick-edit#15]
If the mode parameters are 'ok' or 'cancel', then in the safari browser, when the button is pressed, the action from the mode parameter is always executed.
The buttons work only if the mode parameter is 'ignored'.

**Comment by A1rPun** [comment]
Thanks for your issue, I'll look into this.

Edit: spotted the bug, event params are incorrectly used as booleans

Edit2: it seems that event handlers behave differently in other browsers, this was found by someone in another issue. Decided to scrap the auto-hide feature because it caused many bugs and confusion for the end-user.

**Comment by A1rPun** [comment]
Can't test this issue in safari at the moment but I believe I fixed the issue. Fix will be included in the next update
