### ISSUE TITLE
Detecting IME input before enter pressed

### ISSUE THREAD

**Issue by b4-tahayashi** [A1rPun/vue-quick-edit#5]
When entering text in Japanese / Korean / Chinese, convert and enter using IME.
(ex: `k`+`a` -> `か`)

Therefore, it is necessary to judge the enter of conversion confirmation and the enter which ends edit. Otherwise, it will be submitted during the conversion and the experience will be significantly worse.
Specifically, please judge all cases with keyup.enter instead of `ok`.

refs: 
* https://www.google.com/intl/ja/inputtools/services/features/transliteration.html
* https://stackoverflow.com/questions/7316886/detecting-ime-input-before-enter-pressed-in-javascript/37099672

**Comment by A1rPun** [comment]
Thanks again for another great issue, I will look into this!

**Comment by A1rPun** [comment]
Alright I've looked into it, usually I don't support clashes with browser extensions because that is a never ending story but I'm willing to make a change for this. A couple of options:

1. According to the SO post `keypress` isn't fired in case of an IME input so I could write my `@keyup.enter` to a `@keypress.enter` (I think).
2. I can make the [enter] key customizable so that you can assign a different key for closing the `quick-edit`.
3. Does the IME browser extension has an option to `stopPropagation` on an enter press? If so we could use that or suggest that to Google.
4. ????

**Comment by b4-tahayashi** [comment]
Thank you for your support! IME is not browser extention but software.

I agree with option no.1 too.  Another choise of the implemented keycode 13.(I think either is fine)

x-editable is using keycode 13.

https://github.com/vitalets/x-editable/blob/69221eb7eb230c59c3057df2577fec5fa6341777/src/inputs/text.js#L56

**Comment by A1rPun** [comment]
@b4-tahayashi I will test it using keycodes and keypress this weekend probably. I think I even will make it customizable.

I can only find a browser extension when I search for ["IME"](https://www.google.com/inputtools/services/features/input-method.html).
_**Edit**: I have to look for "Input Method Editors"_

Thank you for the suggestion!

**Comment by A1rPun** [comment]
No time last weekend so I should implement it this week.

**Comment by A1rPun** [comment]
When I try to implement `keypress` I encounter unwanted behaviour but it's not a real issue. You can hold down enter and the input will finitely open and close which causes a flicker.

**Comment by b4-tahayashi** [comment]
awesome!
thankyou for your cooporation!

**Comment by A1rPun** [comment]
No problem. Released in v1.3.0
